#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "pre-commit"

bash | set -eEux

if ! type docker 1>/dev/null; then
  echo "please install docker from docker.com"
  exit 127
fi

# scan for committed secrets
docker run --pull always -v ${PWD}:/ts zricethezav/gitleaks:latest detect --source="/ts" -v

if ! type npx 1>/dev/null; then
  echo "please install npx, see https://nodejs.dev/learn/the-npx-nodejs-package-runner"
  exit 127
fi

npx lint-staged
